spring:
  application:
    name: travel_guide

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.springframework: INFO
    ru.peregruzochka.task_management_system: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n"